// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeGVpP6yvub7LJJQ-_NMeCvWxuLJgjwEE',
    appId: '1:912263981789:web:159a6911cb2095be208934',
    messagingSenderId: '912263981789',
    projectId: 'recipe-7e0f9',
    authDomain: 'recipe-7e0f9.firebaseapp.com',
    storageBucket: 'recipe-7e0f9.appspot.com',
    measurementId: 'G-SVY3Y6C84D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCclk6pm9wIkhvQmOZPaxD_vQhU-9ciQaI',
    appId: '1:912263981789:android:fdfc169c7f3dcc20208934',
    messagingSenderId: '912263981789',
    projectId: 'recipe-7e0f9',
    storageBucket: 'recipe-7e0f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARGHpRC9ZrSOPsp-81hPEHzYmI6KpQ9CI',
    appId: '1:912263981789:ios:0013ea5c42e0a278208934',
    messagingSenderId: '912263981789',
    projectId: 'recipe-7e0f9',
    storageBucket: 'recipe-7e0f9.appspot.com',
    iosBundleId: 'com.example.flutterApplicationRecette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARGHpRC9ZrSOPsp-81hPEHzYmI6KpQ9CI',
    appId: '1:912263981789:ios:08cbaabd7f0f567c208934',
    messagingSenderId: '912263981789',
    projectId: 'recipe-7e0f9',
    storageBucket: 'recipe-7e0f9.appspot.com',
    iosBundleId: 'com.example.flutterApplicationRecette.RunnerTests',
  );
}
